In [2]:
import pandas as pd
import numpy as np

# Mengimport data dari csv
df=pd.read_csv(r"C:\Users\HP\Downloads\Sample_Superstore.csv", encoding='latin-1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [3]:
# Data Understanding

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [4]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [5]:
# Finding missing values and duplicates

missing_values = df.isnull().sum()
percentage_missing = (missing_values / len(df)) * 100
duplicated_values = df.duplicated().sum()

print("Missing Values:")
print(missing_values)

print("\nPercentage of Missing Values:")
print(percentage_missing.round(2))

print("\n" + "=" * 30)

print("Duplicated Values:", duplicated_values)

Missing Values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Percentage of Missing Values:
Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
Quantity         0.0
Discount         0.0
Profit           0.0
dtype: float64

==============================
Duplicated Values: 0

In [6]:
# Checking unique in columns

for col in df.columns:
    jumlah_unik = df[col].nunique()
    print(f"Kolom {col}: {jumlah_unik} nilai unik")

Kolom Row ID: 9994 nilai unik
Kolom Order ID: 5009 nilai unik
Kolom Order Date: 1237 nilai unik
Kolom Ship Date: 1334 nilai unik
Kolom Ship Mode: 4 nilai unik
Kolom Customer ID: 793 nilai unik
Kolom Customer Name: 793 nilai unik
Kolom Segment: 3 nilai unik
Kolom Country: 1 nilai unik
Kolom City: 531 nilai unik
Kolom State: 49 nilai unik
Kolom Postal Code: 631 nilai unik
Kolom Region: 4 nilai unik
Kolom Product ID: 1862 nilai unik
Kolom Category: 3 nilai unik
Kolom Sub-Category: 17 nilai unik
Kolom Product Name: 1850 nilai unik
Kolom Sales: 5825 nilai unik
Kolom Quantity: 14 nilai unik
Kolom Discount: 12 nilai unik
Kolom Profit: 7287 nilai unik

In [7]:
for col in df.columns:
    print(f"\n=== {col} ===")
    print(df[col].unique())

=== Row ID ===
[   1    2    3 ... 9992 9993 9994]

=== Order ID ===
<ArrowStringArray>
['CA-2016-152156', 'CA-2016-138688', 'US-2015-108966', 'CA-2014-115812',
 'CA-2017-114412', 'CA-2016-161389', 'US-2015-118983', 'CA-2014-105893',
 'CA-2014-167164', 'CA-2014-143336',
 ...
 'US-2016-103674', 'US-2015-151435', 'CA-2017-163566', 'US-2016-157728',
 'CA-2015-100251', 'CA-2016-125794', 'CA-2017-163629', 'CA-2014-110422',
 'CA-2017-121258', 'CA-2017-119914']
Length: 5009, dtype: str

=== Order Date ===
<ArrowStringArray>
[ '11/8/2016',  '6/12/2016', '10/11/2015',   '6/9/2014',  '4/15/2017',
  '12/5/2016', '11/22/2015', '11/11/2014',  '5/13/2014',  '8/27/2014',
 ...
 '10/11/2016',  '6/18/2014',  '2/28/2017',   '5/9/2015',  '11/6/2014',
 '12/29/2015',   '4/3/2014',   '6/3/2016',  '4/12/2015',  '1/21/2014']
Length: 1237, dtype: str

=== Ship Date ===
<ArrowStringArray>
['11/11/2016',  '6/16/2016', '10/18/2015',  '6/14/2014',  '4/20/2017',
 '12/10/2016', '11/26/2015', '11/18/2014',  '5/15/2014',   '9/1/2014',
 ...
   '4/6/2017',  '5/13/2015',  '8/19/2014',  '1/20/2017',  '3/28/2015',
  '8/25/2016',  '1/27/2014',  '5/23/2015',  '1/23/2014',   '3/3/2017']
Length: 1334, dtype: str

=== Ship Mode ===
<ArrowStringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

=== Customer ID ===
<ArrowStringArray>
['CG-12520', 'DV-13045', 'SO-20335', 'BH-11710', 'AA-10480', 'IM-15070',
 'HP-14815', 'PK-19075', 'AG-10270', 'ZD-21925',
 ...
 'FW-14395', 'LC-16960', 'HE-14800', 'BD-11560', 'HD-14785', 'CJ-11875',
 'RS-19870', 'SC-20845', 'RE-19405', 'SM-20905']
Length: 793, dtype: str

=== Customer Name ===
<ArrowStringArray>
[       'Claire Gute',    'Darrin Van Huff',     'Sean O'Donnell',
    'Brosina Hoffman',       'Andrew Allen',       'Irene Maddox',
      'Harold Pawlan',          'Pete Kriz',    'Alejandro Grove',
 'Zuschuss Donatelli',
 ...
     'Fred Wasserman',    'Lindsay Castell',       'Harold Engle',
     'Brendan Dodson',      'Harold Dahlen',       'Carl Jackson',
         'Roy Skaria',         'Sung Chung',    'Ricardo Emerson',
  'Susan MacKendrick']
Length: 793, dtype: str

=== Segment ===
<ArrowStringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

=== Country ===
<ArrowStringArray>
['United States']
Length: 1, dtype: str

=== City ===
<ArrowStringArray>
[        'Henderson',       'Los Angeles',   'Fort Lauderdale',
           'Concord',           'Seattle',        'Fort Worth',
           'Madison',       'West Jordan',     'San Francisco',
           'Fremont',
 ...
        'Hagerstown',       'East Orange', 'Arlington Heights',
            'Oswego',       'Coon Rapids',      'San Clemente',
   'San Luis Obispo',        'Springdale',              'Lodi',
             'Mason']
Length: 531, dtype: str

=== State ===
<ArrowStringArray>
[            'Kentucky',           'California',              'Florida',
       'North Carolina',           'Washington',                'Texas',
            'Wisconsin',                 'Utah',             'Nebraska',
         'Pennsylvania',             'Illinois',            'Minnesota',
             'Michigan',             'Delaware',              'Indiana',
             'New York',              'Arizona',             'Virginia',
            'Tennessee',              'Alabama',       'South Carolina',
               'Oregon',             'Colorado',                 'Iowa',
                 'Ohio',             'Missouri',             'Oklahoma',
           'New Mexico',            'Louisiana',          'Connecticut',
           'New Jersey',        'Massachusetts',              'Georgia',
               'Nevada',         'Rhode Island',          'Mississippi',
             'Arkansas',              'Montana',        'New Hampshire',
             'Maryland', 'District of Columbia',               'Kansas',
              'Vermont',                'Maine',         'South Dakota',
                'Idaho',         'North Dakota',              'Wyoming',
        'West Virginia']
Length: 49, dtype: str

=== Postal Code ===
[42420 90036 33311 90032 28027 98103 76106 53711 84084 94109 68025 19140
 84057 90049 77095 75080 77041 60540 32935 55122 48185 19901 47150 10024
 12180 90004 60610 85234 22153 10009 49201 38109 77070 35601 94122 27707
 60623 29203 55901 55407 97206 55106 80013 28205 60462 10035 50322 43229
 37620 19805 61701 85023 95661 64055 91104 43055 53132 85254 95123 98105
 98115 73034 90045 19134 88220 78207 77036 62521 71203  6824 75051 92374
 45011  7090 19120 44312 80219 75220 37064 90604 48601 44256 43017 48227
 38401 33614 95051 55044 92037 77506 94513 27514  7960 45231 94110 90301
 33319 80906  7109 48180  8701 22204 80004  7601 33710 19143 90805 92345
 37130 84041 78745  1852 31907  6040 78550 85705 62301  2038 33024 98198
 61604 89115  2886 33180 28403 92646 40475 80027  1841 39212 48187 10801
 28052 32216 47201 13021 73071 94521 60068 79109 11757 90008 92024 77340
 14609 72701 92627 80134 30318 64118 59405 48234 33801 36116 85204 60653
 54302 45503 92804 98270 97301 78041 75217 43123 10011 48126 31088 94591
 92691 48307  7060 85635 98661 60505 76017 40214 75081 44105 75701 27217
 22980 19013 27511 32137 10550 48205 33012 11572 92105 60201 48183 55016
 71111 50315 93534 23223 28806 92530 68104 98026 92704 53209 41042 44052
  7036 93905  8901 17602  3301 21044 75043  6360 22304 43615 87401 92503
 90503 78664 92054 33433 23464 92563 28540 52601 98502 20016 65109 63376
 61107 33142 78521 10701 94601 28110 20735 30076 72401 47374 94509 33030
 46350 48911 44221 89502 22801 92025 48073 20852 33065 14215 33437 39503
 93727 27834 11561 35630 31204 52402  2908 81001 94533 32725 42071  6457
 11520 90660 84604 84062 30080 24153 44134 36608  2740 75061  8360 85301
 14304 27360 92683 38301 75019 91767 89031 18103 19711 85281 92677  8302
  2149 13601 54915 98006 75002 79907 76051 75007 37167 98031 70506 97224
 60076 75023 23434 46203  7002 28314 27405 21215 53142 66062 98002 74133
 97756 27604 74403  6450 42104 46614  6010 89015 99207 76248 45014 32127
 97504 22901 59801 33178 29501 97477 32712 19601 80020 65807  7501 73120
 23320 79424 65203 37604 36830 92404  1453 59715 85345 44107  8861 91761
 91730 56560 75150 95207 32174 94086  3820 17403 77840 63116  2169 95336
 44240 76903 84106 35810 37918 72209 48146 43302 80122  5408  4401 38671
 47362 48640 57103 80525 47905 37042 95823 91360  2148  1040 87105 89431
 92236 60126  7055 29406 23602 14701 46544 43402 92253 32303 37211 98226
 60098 76117 60090 29483 71901 80112 43130 88001 35244 75034 95687 84107
 53186 93309 33068 45373 78415 90278 32839  7050 70601 60035 11550 46060
 55124 29464 48310 54703 78577 59102 97030 37421 83642 92307 60440 55369
 95695 77489 77581 94403 49505 93277 66212 92592 92399  2151 77301 60477
 52001 48127 87505 28601 60188 56301 33161 46226 33317 34952 29730 79762
 53214 91911 66502 16602 80229 61821 47401 71854 78539 77520 46142 90712
  2895 54880 76021 98042 74012 33023 33021 77536 67212 78501 52240 83704
  2920 61032 77642 95610 75056 98052 32114 86442 46368 58103 46514 91776
 33063 30328 44060 73505 23666 13440 54601 83501 39401 94526 48858 84321
  6708 30605  4240 61832 85323 30062 85364 54401 99301 60302 32503 77573
 20877 84043 35401 92553 40324 80538 85224 59601 63122 76706 48066 60423
 18018 55113 68801 55125 48237 72756 88101 33458 93101 75104 68701 84020
 48104 91941 83201 49423  6460 60089 92630 96003 95928 13501 72032 82001
 42301 83605 70065  3060 38134 94061 37087 93454 60016 98632 37075 50701
  2138 60067  1915 97405 93030 98059 60025 33445 80022 77590 27893 87124
 27534 98208 90640 92020 77705 33407 79605 61761 63301 60174 93010 97123
 91505 95351 67846  8401 80501 95616 26003 95037  7011 53081 30344 57701
  1810 34741  6484  6810 52302 32771 78666 80634 76063 44035 83301 33134
 60441  1752 20707 77803 71603 57401 21740  7017 60004 60543 55433 92672
 94568 93405 72762 95240 77571 45040 30188]

=== Region ===
<ArrowStringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

=== Product ID ===
<ArrowStringArray>
['FUR-BO-10001798', 'FUR-CH-10000454', 'OFF-LA-10000240', 'FUR-TA-10000577',
 'OFF-ST-10000760', 'FUR-FU-10001487', 'OFF-AR-10002833', 'TEC-PH-10002275',
 'OFF-BI-10003910', 'OFF-AP-10002892',
 ...
 'OFF-LA-10004677', 'FUR-CH-10002780', 'OFF-EN-10001535', 'TEC-MA-10003493',
 'TEC-AC-10002380', 'TEC-PH-10002817', 'TEC-MA-10003589', 'OFF-AP-10003099',
 'TEC-PH-10002645', 'OFF-ST-10001627']
Length: 1862, dtype: str

=== Category ===
<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

=== Sub-Category ===
<ArrowStringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

=== Product Name ===
<ArrowStringArray>
[                               'Bush Somerset Collection Bookcase',
      'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
        'Self-Adhesive Address Labels for Typewriters by Universal',
                    'Bretford CR4500 Series Slim Rectangular Table',
                                   'Eldon Fold 'N Roll Cart System',
 'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood',
                                                       'Newell 322',
                                   'Mitel 5320 IP Phone VoIP phone',
             'DXL Angle-View Binders with Locking Rings by Samsill',
                                 'Belkin F5C206VTEL 6 Outlet Surge',
 ...
  'Self-Adhesive Address Labels for Typewriters with Dispenser Box',
             'Office Star - Task Chair with Contemporary Loop Arms',
                                              'Grip Seal Envelopes',
                              'Penpower WorldCard Pro Card Scanner',
                     'Sony 8GB Class 10 Micro SDHC R40 Memory Card',
                                  'RCA ViSYS 25425RE1 Corded phone',
                                     'Cisco 8961 IP Phone Charcoal',
                                      'Eureka Hand Vacuum, Bagless',
                                                            'LG G2',
           'Eldon Jumbo ProFile Portable File Boxes Graphite/Black']
Length: 1850, dtype: str

=== Sales ===
[261.96  731.94   14.62  ... 437.472  97.98  243.16 ]

=== Quantity ===
[ 2  3  5  7  4  6  9  1  8 14 11 13 10 12]

=== Discount ===
[0.   0.45 0.2  0.8  0.3  0.5  0.7  0.6  0.32 0.1  0.4  0.15]

=== Profit ===
[ 41.9136 219.582    6.8714 ...  16.124    4.1028  72.948 ]

In [8]:
# Data Cleaning

# Create a copy of the original DataFrame
df_clean = df.copy()

In [9]:
# Mengubah order date dan ship date menjadi datetime

df_clean['Order Date'] = pd.to_datetime(df_clean['Order Date'])
df_clean['Ship Date'] = pd.to_datetime(df_clean['Ship Date'])
df_clean['Postal Code'] = df_clean['Postal Code'].astype(str)
df_clean

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [10]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   str
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(14)
memory usage: 3.2 MB

In [11]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
# Ekspor ke csv
df_clean.to_excel("Sample_Superstore_Clean.xlsx", index=False)